### ISSUE TITLE
Potential gc strategy

### ISSUE THREAD

**Issue by cablehead** [imgix/levee#19]
This gist is an experiment for a potential strategy for using gc to clean up things like abandoned file descriptor references:

https://gist.github.com/cablehead/29c65b2047a165731063fd998e91b5ea

Interestingly, run this snippet with luajit, vs levee run.

I'm guessing luajit does a garbage collect before exiting...

\cc @kalamay

**Comment by cablehead** [comment]
Other uses: deregister this service from consul on process exit

**Comment by kalamay** [comment]
Yeah, that would work. It requires either an `ffi.new` or a `C.malloc`. It does garbage collect on a clean exit, but it wouldn't for any abort or a `C.exit`. I don't know about `os.exit`, but it might not there either.

**Comment by cablehead** [comment]
Quick test suggests it doesn't work for `os.exit` either ...

**Comment by cablehead** [comment]
I'm thinking through either making this type of pattern common; or having a `defer` function you can register clean up code to run after a well defined block completes.. or both.

The `defer` approach would have the same limitations with regards to C.exit and os.exit, if they're used inside a block that has pending cleanup.

**Comment by kalamay** [comment]
We could hook something up with `attest(3)`. That would fire for the `os.exit` and `C.exit` cases. Not the crash or lua panic cases (anything that aborts), but it would allow for some global cleanup.

**Comment by cablehead** [comment]
Interesting... *beard stroke*

**Comment by kalamay** [comment]
I think the proper abstraction would be a single `atexit` function registered for each state and that can delegate to all cleanup. You can pass a lua function to a C function pointer, and luajit will do the right thing. But they are a bit costly, so you'd not want to create one for everything that needs to be cleaned up.

**Comment by kalamay** [comment]
Hmm, or maybe one per hub instance? A list that could be attached per spawned "thing"? It would still be nice to attach a deferred to the lifetime of a spawned thing...  *beard stroking intensifies*

**Comment by cablehead** [comment]
Can we just ensure that atexit calls lua_close for any open states? I think that will then fire all gc's?

Levee's `main.c` is calling `lua_close`, so I can't see why gc's aren't working for `levee run`...

**Comment by cablehead** [comment]
Ugh, nevermind!

https://github.com/imgix/levee/blob/master/levee/main.lua#L64

I'm a goon

**Comment by cablehead** [comment]
The nice thing about relying on gc versus an explicit `defer` is the granularity just takes care of itself...

**Comment by cablehead** [comment]
This overcomes the `os.exit` in levee's `main.lua`:

https://github.com/imgix/levee/tree/atexit-experiment

**Comment by kalamay** [comment]
Are there any competing code paths to call `levee_destroy`? After calling that, its probably best to `NULL` the value holding the state. Also need to think through threading a bit.

**Comment by cablehead** [comment]
Yeah definitely. `levee_destroy` / `destroy` do set `self->L = NULL`, but not the entire state (`self`)

**Comment by kalamay** [comment]
Right, the entire state is the part I'm referring to. Its not safe to call `levee_destroy` twice without setting to `NULL`:

```C
levee_destroy (state);
levee_destroy (state); // NOT OK
```

vs:

```C
levee_destroy (state);
state = NULL;
levee_destroy (state); // SAFE
```

**Comment by cablehead** [comment]
What do you think about `destroy` taking `&state`, so it can set it to `NULL`?

https://github.com/imgix/levee/blob/master/src/levee.c#L199
https://github.com/imgix/levee/blob/master/src/levee.c#L187

**Comment by cablehead** [comment]
ie, something like: https://github.com/imgix/levee/commit/5ea8e57c5ef61cf37b9d04582620f49edc70e20f

**Comment by cablehead** [comment]
Now that `atexit` is set to destroy the main levee state, we should be able to begin experimenting with using cdata GCs.
