### ISSUE TITLE
update dialer's writer to use the new `:writeinto_iovec(iov)` interface

### ISSUE THREAD

**Issue by cablehead** [imgix/levee#23]

**Comment by kalamay** [comment]
I actually do have this, I just added the wrong file to the commit. Oops, fixing now. :/

**Comment by cablehead** [comment]
Sweet!

**Comment by kalamay** [comment]
This makes sense right? https://github.com/imgix/levee/pull/22/commits/85c2d85a4e6d465f2ef9582fe4112733aadb5147

**Comment by cablehead** [comment]
Yep, it does. This already looks like a pattern we might be able to capture. W:send takes a `...` .. it might be able to effectively translate to this.  85c2d85 seems good though until we do this sort of thing a few more times.

**Comment by kalamay** [comment]
Ah, yeah. I was thinking `Message` could capture a full array as a general purpose iovec writer, but that would be nicer. I suppose I could have done this with the nested Iovec too. Good for now though.

**Comment by cablehead** [comment]
Yeah, it's nice to let things stew a bit, before committing to it.

**Comment by cablehead** [comment]
Fixed by #22
