### ISSUE TITLE
Async DNS resolver

### ISSUE THREAD

**Issue by cablehead** [imgix/levee#35]
At the moment we are using the getaddrinfo system call to resolve. This is a blocking call, so we run it in a thread, which is really ganky. It'd be fantastic to have a pure Lua DNS resolver that uses Levee in order to be async.

**Comment by thelinuxkid** [comment]
Could we use an existing async DNS library and wrap Levee around it? For example
[adns](https://www.gnu.org/software/adns/) or [dns.c](https://github.com/wahern/dns).

**Comment by cablehead** [comment]
Yeah, it'd be great to wrap an existing lib if one exists. Picking one might be tough. Ideally it'd have no external dependencies, have a license that means we can statically link to it, is sane, simple, stable and easy to use, and have an easy way to integrate with levee's poller.

**Comment by thelinuxkid** [comment]
I'll take a closer look at these two

**Comment by cablehead** [comment]
The only other one that I found with a quick search was: https://github.com/c-ares/c-ares

**Comment by thelinuxkid** [comment]
Thanks
