### ISSUE TITLE
TLS support in levee not working

### ISSUE THREAD

**Issue by copyconstruct** [imgix/levee#42]
Maybe I'm doing something wrong, but the TLS bindings don't seem to work. I have LibreSSL installed on my machine fwiw, but am still seeing this when I run the test `test_tls` (I renamed the test `test_tls_in_http` on my local branch) in the `test_http.lua` module:

```[cindy@localhost][levee]*[master]$ levee test -vv ./tests/ -k test_tls_in_http
zsh: correct 'test' to 'tests' [nyae]? n
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
 ....
        INFO  2017-07-28T13:33:18.201912-07:00  4107 levee.app.consul     ==> Starting Consul agent...
        INFO  2017-07-28T13:33:18.250995-07:00  4107 levee.app.consul     ==> Consul agent running!
        INFO  2017-07-28T13:33:18.251064-07:00  4107 levee.app.consul                Version: 'v0.8.3'

...
        INFO  2017-07-28T13:33:18.313001-07:00  4107 levee.app.consul         2017/07/28 13:33:18 [INFO] agent: Deregistered service 'foo'
        INFO  2017-07-28T13:33:18.313032-07:00  4107 levee.app.consul         2017/07/28 13:33:18 [DEBUG] agent: Node info in sync
        INFO  2017-07-28T13:33:18.313058-07:00  4107 levee.app.consul         2017/07/28 13:33:18 [DEBUG] http: Request GET /v1/agent/service/deregister/foo (284.852µs) from=127.0.0.1:50552
./tests/p/test_http.lua
    test_tls_in_http                         ERROR TLS %s	generic TLS error (tls.SERVER)
        FATAL 2017-07-28T13:33:18.323613-07:00  4107 levee.core.hub       stack traceback:
	[C]: in function 'assert'
	/Users/cindysridharan/Imgix/levee/levee/net/stream.lua:40: in function </Users/cindysridharan/Imgix/levee/levee/net/stream.lua:19>

/Users/cindysridharan/Imgix/levee/levee/net/stream.lua:40: assertion failed!
```

I see a few problems with this - 
1. First, I don't see the need for to spin up a Consul process. We're only testing if we can make a https request with levee. In all the levee apps I author, I inject Consul as a dependency which gets mocked out in tests. Happy to fix this myself, but maybe there's a reason behind why it's set up this way?
2. The assert [in the code](https://github.com/imgix/levee/blob/master/levee/net/stream.lua#L37-L42) is super janky - I'm guessing it was added as a pert of development but never cleaned up? In general, as a client of levee (or any other library), I except an error to be bubbled up to me so I can decide how best I want to handle it. I don't want to code to barf because the library is making an assertion.
3. The TLS bit itself isn't working for me. I also find the API a tad unintuitive - Like, why am I expected to pass in a CA file every time I make a request? It should pick up the system default. It's possible that I'm misunderstanding how to use the API (docs are vague), but if I need to pass in that option [here](https://github.com/zebrafishlabs/sentinel/pull/66/files#diff-31c093f0f4c5a37a206d2c7a01a9b874R31) - that test is failing with an ECONNREFUSED error.

**Comment by copyconstruct** [comment]
cc @cablehead @thelinuxkid

**Comment by thelinuxkid** [comment]
1. I have never had the consul test run. It looks to me from a brief look that it gets triggered if consul is running: https://github.com/imgix/levee/blob/master/tests/app/test_consul.lua#L5
2. You’re right about the asserts. There should be a better way. I will talk to Andy about that when he’s back online
3. I installed Libressl v2.6.0 from source on OSX and Linux

**Comment by copyconstruct** [comment]
Sorry for the dilatory response. So I managed to get this working by linking sentinel against LibreSSL v2.5.3 two weeks ago, but it should be working with the latest release as well. cc @kalamay

**Comment by thelinuxkid** [comment]
The error I got when building the latest version was independent from our integration. It could be a good idea to wait until a compilable version comes out. Still. I will run it by @cablehead

**Comment by cablehead** [comment]
Thinking it'd be good to get @kalamay's input. He might have a suggestion off the top his head that'll just clear things up.

**Comment by kalamay** [comment]
Just to be clear, you're waiting for a compilable version of levee or libressl? Both levee master and libressl 2.5.5 build fine for me on Ubuntu 14.04 and Mac OS 10.12.6.

**Comment by cablehead** [comment]
Cindy, are you still have issues building with the latest version of libressl?

**Comment by copyconstruct** [comment]
@cablehead I used LibreSSL 2.6, instead of 2.5.5, which was the latest stable release. 2.5.5 works.

That said, I'm seeing another problem. In short, I'm not getting a body back from requests made via levee. Sentinel logs

```INFO  2017-09-13T22:27:10.799439Z 25956 sentinel             Request GET xxx to api.imgix.com from xxx
INFO  2017-09-13T22:27:10.803332Z 25956 levee.net.dialer     SYNC: xxx
INFO  2017-09-13T22:27:10.920466Z 25956 sentinel             ConnectTLS: response code 200 body nil
INFO  2017-09-13T22:27:10.920593Z 25956 sentinel             xxx failed - code 200 body nil```

**Comment by cablehead** [comment]
Turn between fixing, or beginning to switch Sentinel over to Levee 0.4's new HTTP API. Will have a solution for you before your Friday.

**Comment by cablehead** [comment]
It looks like google respond with chunk transfer. With the current HTTP API, there's no body attribute for chunked responses. 

There's a `:tostring` method directly on the response object with normalizes between chunked and non-chunched responses.

```
response.body = resp:tostring()
```
