### ISSUE TITLE
Test error with async DNS on OS X

### ISSUE THREAD

**Issue by cablehead** [imgix/levee#44]
I've finally merged this branch! Just seeing:

```
$ levee test -vv ./tests/  -k test_core_async
```

```
-----
./tests/net/test_dialer.lua: 47
  --> __test_core(true)

./tests/net/test_dialer.lua: 32
  --> assert.equal(err, want)

unknown node or service (addr.ENONAME) ~= Non-existent Domain (dns.NXDOMAIN)
```

**Comment by thelinuxkid** [comment]
It works for me. This test relies on the nameserver(s) in `/etc/resolv.conf`. Maybe what's happening is your DNS server is returning zero results instead of an error. One way to mitigate this would be to pass a mock DNS server's host:port to `net.dialer`, as an option. That's what most of `net.test_dns` does. It's not a great solution though. What's your output for
`dig kdkd`?

**Comment by cablehead** [comment]
I get this:

```
$ dig kdkd

; <<>> DiG 9.8.3-P1 <<>> kdkd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58780
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kdkd.                          IN      A

;; Query time: 5 msec
;; SERVER: 2001:4528:6020:bee:6c69:51ff:fefd:db13#53(2001:4528:6020:bee:6c69:51ff:fefd:db13)
;; WHEN: Tue Aug 22 15:49:00 2017
;; MSG SIZE  rcvd: 22
```

**Comment by cablehead** [comment]
Would it be easy to test of zero results are returned, and then simulate the `dns.NXDOMAIN` error?

**Comment by cablehead** [comment]
Actually, that test is passing for me now too.. I wonder if it was the connection I had when I ran it? My internet options here are very flakey

**Comment by thelinuxkid** [comment]
Yeah, so, your response has `status: NOERROR` but also no `ANSWER SECTION`. Compare to mine with `status: NXDOMAIN`:
```; <<>> DiG 9.9.5-3ubuntu0.14-Ubuntu <<>> kdkd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 40193
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kdkd.                          IN      A

;; Query time: 35 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Tue Aug 22 12:24:57 PDT 2017
;; MSG SIZE  rcvd: 22
```

You are probably reaching a different DNS server now which is returning the correct response. 

Empty Non-Terminal (`ENT`), i.e., a response code of `NOERROR` and an empty answer section, is different from `NXDOMAIN` ([rfc8020](https://tools.ietf.org/html/rfc8020#section-3.1)). Maybe for our purposes, however, it's fine to make them equal? If not, we need to at least change `EAI_NONAME` to `EAI_NODATA`, which is the recommended response for `ENT`.

**Comment by cablehead** [comment]
Perhaps have it return `EAI_NODATA ` instead of `EAI_NONAME` for this case, and have the test assert the response is either `EAI_NODATA` or `dns.NXDOMAIN`?

**Comment by thelinuxkid** [comment]
Sounds good

**Comment by thelinuxkid** [comment]
change pushed to `andres-dns` branch
