### ISSUE TITLE
Potentially make use of sha1 in libressl

### ISSUE THREAD

**Issue by cablehead** [imgix/levee#46]
That would mean websockets would require libressl to be installed, even when not being used over tls, but it would also consolidate our crypto implementations. 

Currently we have: https://github.com/imgix/levee/blob/a41ca1f0a40acb3e26c363d3301ee4bf6db8f8f7/levee/p/sha1.lua

\cc @kalamay 

What do we think?

**Comment by thelinuxkid** [comment]
Yeah. I've never felt great about including that library. I was going to bring it up at a later point, before the feature was finished. Since the encoding and decoding are moving to siphon, I'll make use of the libressl sha1 there.

**Comment by cablehead** [comment]
@kalamay any concerns with adding libressl as a conditional dependency (websockets) to siphon?

**Comment by kalamay** [comment]
I don't have any particular concerns, but it wouldn't be my first approach. This is a bit off my radar at the moment, so I don't have a clear picture of the trade-offs here. That said, my first approach would be to specify init/update/final function pointer types, and require those for the parser. That keeps the the implementation up to the library user, so any library could be used (openssl, libressl, nettle, etc.)

Off the cuff, something like this:

```C
struct SpDigest {
    int (*init)(void *ctx);
    int (*update)(void *ctx, const void *data, size_t len);
    int (*final)(unsigned char *md, void *ctx);
};

int sp_ws_init(SpWS *ws, const SpDigest *digest);
```

Levee would then plug the libressl sha1 functions into that, and pass the struct to the parser. This type would then work well for other digest needs as they arise yet keep the usage flexible.

**Comment by cablehead** [comment]
Oo, that approach seems nice..

**Comment by cablehead** [comment]
I close this for now, if Jeremy's suggested approach seems good to you @thelinuxkid 

Just reopen if you'd like to discuss other options.

**Comment by thelinuxkid** [comment]
Seems good to me
