### ISSUE TITLE
Think through whether port should be able to be a string

### ISSUE THREAD

**Issue by cablehead** [imgix/levee#47]
At the moment if you pass port as a string, it will error here:

https://github.com/imgix/levee/blob/master/levee/net/dialer.lua#L77

\cc @thelinuxkid

**Comment by thelinuxkid** [comment]
One solution could be a combination of `strtol(service, NULL, 10);` to convert to an int and `getservbyname(service)` to get the service port, if `strtol` produces an error.

**Comment by thelinuxkid** [comment]
I say `strtol(service, NULL, 10);` and not `atoi` because:

```
The atoi() function converts the initial portion of the string pointed to by nptr to int.  The behavior is the same as

    strtol(nptr, NULL, 10);

except that atoi() does not detect errors.
```

**Comment by kalamay** [comment]
Just jumping in, I'd recommend:

```
char *end;
long port = strtol(nptr, &end, 10);
if (*end != '\0') {
    // not a number, so try converting service name to port with getservbyname
}
if (port < 0 || port > 65535) {
    // handle invalid port
}
```

**Comment by cablehead** [comment]
Thanks for the input. I'll field this one, and do as suggested.

**Comment by cablehead** [comment]
I just used Lua's `tonumber` vs `strtol` since the code for this is all in Lua land.
